name: Logs demo

on:
  workflow_dispatch:
permissions:
  contents: read
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  show-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show Local Tags
        run: git tag

      - name: Show Remote Tags
        run: git ls-remote --tags origin

      - name: Get Latest Tag
        id: get_latest_tags
        run: |
          # Fetch tags from the remote repository
          git fetch --tags

          # Get the latest tag for the current commit
          # latest_tag=$(git describe --tags --abbrev=0 HEAD --always)
          
          # If the above command fails, try using the following
          latest_tag=$(git tag --points-at HEAD)

          echo "Latest Tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"
