name: cgt outputs

on:
  workflow_dispatch:

jobs:
  write-job:
    runs-on: ubuntu-latest
    outputs:
      my_value: ${{ steps.generate.outputs.my_value }}
    steps:
    - name: Generate value
      id: generate
      run: |
        echo "my_value=hello" >> $GITHUB_ENV
        echo "my_value_output=hello" >> $GITHUB_ENV
      env:
        my_value_output: hello

  read-job:
    runs-on: ubuntu-latest
    needs: write-job
    steps:
      - name: Use value
        run: |
          echo "Value is $my_value_output"
        env:
          my_value_output: ${{ needs.write-job.outputs.my_value }}
