name: cgt outputs

on:
  workflow_dispatch:

jobs:
  write-job:
    runs-on: ubuntu-latest
    outputs:
      my_value: ${{ steps.generate.outputs.my_value }}
    steps:
    - name: Generate value
      id: generate
      run: |
        echo "my_value=hello" >> $GITHUB_ENV
        echo "::set-output name=my_value::hello"

  read-job:
    runs-on: ubuntu-latest
    needs: write-job
    steps:
      - name: Use value
        run: |
          echo "my_value=${{ needs.write-job.outputs.my_value }}" >> $GITHUB_ENV
          echo "Value is $my_value"
        env:
          my_value: ${{ needs.write-job.outputs.my_value }}
