name: cgt outputs

on:
  workflow_dispatch:

jobs:
  write-job:
    runs-on: ubuntu-latest
    outputs:
      my_value: ${{ steps.generate.outputs.my_value }}
    steps:
    - name: Generate value
      id: generate
      run: echo "my_value=hello" >> $GITHUB_ENV
      env:
        my_value: hello

  read-job:
    runs-on: ubuntu-latest
    needs: write-job
    steps:
      - name: Use value
        run: echo "Value is ${{ needs.write-job.outputs.my_value }}"
