name: New outputs

on:
  workflow_dispatch:

jobs:
  write-job:
    runs-on: ubuntu-latest
    steps:
    - name: Generate value
      id: generate
      run: echo "myvalue=hello" >> GITHUB_OUTPUT
    outputs:
      myvalue: ${{ steps.generate.outputs.myvalue }}

  read-job:
    runs-on: ubuntu-latest
    needs: write-job
    steps:
    - name: Use value
      run: echo "${{ needs.write-job.outputs.myvalue }}"
