name: Test outputs

on:
  workflow_dispatch:

jobs:
  write-job:
    runs-on: ubuntu-latest
    outputs:
      my_value: ${{ steps.generate.outputs.myvalue }}
    steps:
    - name: Generate value
      id: generate
      run: echo "myvalue=hello"

  read-job:
    runs-on: ubuntu-latest
    needs: write-job
    steps:
      - name: Use value
        run: echo ${{ steps.write-job.outputs.my_value }}
        
