name: PR number test
on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
permissions: write-all
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      # with:
      #   fetch-depth: 0 # Fetch all history for accurate diffs

    - name: Get PR
      id: get_pr
      run: |
        echo "target_branch= ${{ github.base_ref }}"
        echo "current_branch= ${{ github.head_ref }}"
        echo "${{ github.event_name }}"
        echo "${{ github.event.pull_request.number }}"
        git fetch origin '+refs/pull/${PR_NUMBER}/head:refs/remotes/origin/pr/${PR_NUMBER}'
    
