name: Release with symver demo

on:
  workflow_dispatch:
    inputs:
      tag_ver:
        description: 'Enter tag version'
        required: true
        default: '1.0.0'
permissions:
  contents: write

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag_ver: ${{ steps.set_tag.outputs.TAG_VER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tag name
        id: set_tag
        run: |
          echo "TAG_VER=v${{ github.event.inputs.tag_ver }}" >> $GITHUB_OUTPUT

      - name: Create and Push tag
        run: |
          git tag $TAG_VER
          echo "Created tag: $TAG_VER"
          git push origin $TAG_VER
          echo "$TAG_VER tag pushed"

  publish-release:
    needs: tag-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag-and-push.outputs.tag_ver }}
          release_name: ${{ needs.tag-and-push.outputs.tag_ver }}
          body: |
            Changes in this Release:
          draft: false
          prerelease: false
          
  change-log:
    needs: publish-release
    runs-on: ubuntu-latest
    outputs:
      previous_tag: ${{ steps.get_previous_tag.outputs.previous_tag }}
    steps:
      - name: Get Previous Tag
        id: get_previous_tag
        run: |
          echo "inside changelog..."
          echo "previous_tag=$(git describe --tags --abbrev=0)"
      - name: Generate Changelog
        id: generate_changelog
        run: |
          # Assuming your changelog format is based on commit messages
          changelog=$(git log --pretty=format:"- %s" "${{ steps.get_previous_tag.outputs.previous_tag }}"..HEAD)
          echo "$changelog" > changelog.md
          echo changelog.md
      
    
  

#================================================================================
# Below workflow creates, pushes a tag + create a release
# WORKED

# name: Release demo

# on:
#   workflow_dispatch:
# permissions:
#   contents: write

# jobs:
#   tag-and-push:
#     runs-on: ubuntu-latest
#     outputs:
#       tag_name: ${{ steps.set_tag.outputs.tag_name }}
#     steps:
    
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set tag name
#         id: set_tag
#         run: echo "TAG_NAME=v$(date +'%d%m%Y-%H%M%S')" >> $GITHUB_OUTPUT
      
#       - name: Debug tag_name
#         run: echo "tag_name=$TAG_NAME"

#       - name: Create and Push tag
#         run: |
#           git tag $TAG_NAME
#           echo "Created tag: $TAG_NAME"
#           git push origin $TAG_NAME
#           echo "$TAG_NAME tag pushed"

#   publish-release:
#     needs: tag-and-push
#     runs-on: ubuntu-latest
#     steps:
#       - name: Publish Release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ needs.tag-and-push.outputs.tag_name }}
#           release_name: Release-${{ needs.tag-and-push.outputs.tag_name }}
#           body: |
#             Changes in this Release:
#           draft: false
#           prerelease: false
