name: Test-release

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - b1
  #     - master
  #   types:
  #     - opened
  #     - synchronize
  #     - closed
permissions:
  contents: write
  
jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    steps:
      # if: github-event.pull_request.base.ref == 'master'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and Push tag
        run: |
          TAG_NAME="v$(date +'%d%m%Y-%H%M%S')"
          echo $TAG_NAME >> $GITHUB_ENV
          git tag $TAG_NAME
          echo "Created tag: $TAG_NAME"
          git push origin $TAG_NAME
          echo "$TAG_NAME tag pushed"
      
      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $TAG_NAME
          release_name: Release-$TAG_NAME
          body: |
            Changes in this Release:
          draft: false
          prerelease: false
          
