name: Release demo

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.set_tag.outputs.tag_name }}
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tag name
        id: set_tag
        run: echo "TAG_NAME=v$(date +'%d%m%Y-%H%M%S')" >> $GITHUB_OUTPUT
      
      - name: Debug tag_name
        run: echo "tag_name=$TAG_NAME"

      - name: Create and Push tag
        run: |
          git tag $TAG_NAME
          echo "Created tag: $TAG_NAME"
          git push origin $TAG_NAME
          echo "$TAG_NAME tag pushed"

  publish-release:
    needs: tag-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag-and-push.outputs.tag_name }}
          release_name: Release-${{ needs.tag-and-push.outputs.tag_name }}
          body: |
            Changes in this Release:
          draft: false
          prerelease: false
