name: Symver with inputs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version number'
        required: true
        default: '1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print inputs
        run: |
          echo "Version: ${{ github.event.inputs.version }}"
