name: Tags-diff - demo

on:
  workflow_dispatch:
  
permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      current_tag: ${{ steps.get-tags.outputs.current_tag }}
      previous_tag: ${{ steps.get-tags.outputs.previous_tag }}
      # diff_content: ${{ steps.tag-diff.outputs.diff_content }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for tags and history - (important)

      - name: Get Tags
        id: get-tags
        run: |
          echo "Current Tag:"
          current_tag=$(git describe --tags --abbrev=0)
          echo $current_tag
          
          echo "Previous Tag:"
          previous_tag=$(git tag --sort=-v:refname | grep -A1 $current_tag | tail -1)
          # Ensure it's not outputting the current tag as previous (if no previous tag exists)
          if [ "$previous_tag" == "$current_tag" ]; then
            previous_tag=""
          fi
          echo $previous_tag

          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
          echo "previous_tag=$previous_tag" >> $GITHUB_OUTPUT

      # Example of using the output
      # - name: Echo Tags
      #   run: |
      #     echo "Current Tag: ${{ steps.tags.outputs.current_tag }}"
      #     echo "Previous Tag: ${{ steps.tags.outputs.previous_tag }}"
      
  tag-diff:
    runs-on: ubuntu-latest
    needs: tags
    steps:
      - name: tag diff
        run: |
          previous_tag=${{ needs.tags.outputs.previous_tag }}
          current_tag=${{ needs.tags.outputs.current_tag }}
          echo "previous tag= $previous_tag"
          echo "current tag= $current_tag"
          
          if [ -z "$previous_tag" ] || [ -z "$current_tag" ]; then
            echo "One of the tags is missing; cannot show diff."
            diff_content="No previous tag found to compare."
          else
            diff_content=git diff $previous_tag $current_tag
            echo $diff_content
          fi
          
          # Limit the diff content to avoid exceeding max comment length
          diff_content=${diff_content:0:65000}
          # git diff ${{ steps.tags.outputs.current_tag }}..${{ steps.tags.outputs.previous_tag }}

      # - name: Comment on PR
      #   uses: actions/github-script@v5
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       const issue_number = context.issue.number;
      #       const diff_content = `${{ steps.generate_diff.outputs.diff_content }}`;
      #       const comment_body = `### Code Differences:\n\`\`\`diff\n${diff_content}\n\`\`\``;
      #       github.rest.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: issue_number,
      #         body: comment_body
      #       });


