name: Tags demo

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  test-tags:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Latest Tag
        id: get_latest_tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git describe --tags --abbrev=0

      